# 激活的配置文件(默认dev,打包时会被Maven profile替换)
spring:
  profiles:
    active: @spring.profiles.active@
  config:
    import: classpath:config/redis/redis-key.yml

# MyBatis 配置
mybatis:
  mapper-locations: classpath:com/gis/xian/mapper/*.xml
  type-aliases-package: com.gis.xian.entity
  configuration:
    map-underscore-to-camel-case: true
  # 添加 TypeHandler 扫描包路径
  type-handlers-package: com.gis.xian.handler
