# 安全配置
safety:
  sm2:
    # sm2公钥在redis存储名
    global: 'xian:sm2:keypair:global'


# 初始化数据存储
init:
  data:
    # 基础信息点数据：滑坡、泥石流、山洪、内涝
    base-points:
      hidden-danger:
        rainstorm: 'xian:init:data:base-points:hidden-danger:rainstorm'
        earthquake: 'xian:init:data:base-points:hidden-danger:earthquake'
      risk: 'xian:init:data:base-points:risk'
      hospitals: 'xian:init:data:base-points:hospitals'
      dangerous-source: 'xian:init:data:base-points:dangerous-source'
      emergency-shelter: 'xian:init:data:base-points:emergency-shelter'