spring:
  datasource:
    # Druid 公共配置
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: false

    # 主库
    master:
      url: jdbc:postgresql://10.22.245.138:54321/xianDC?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: zaihailian
      password: XAYJ@gis2603
      driver-class-name: org.postgresql.Driver

    # 从库
    slave:
      url: jdbc:postgresql://10.22.245.138:54321/xianDCAccess?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: zaihailian
      password: XAYJ@gis2603
      driver-class-name: org.postgresql.Driver

    slave1:
      url: jdbc:postgresql://47.92.216.173:7654/yjzyk_xian?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&postgis=true
      username: postgres
      password: zhangsan
      driver-class-name: org.postgresql.Driver
